#!/usr/bin/env bash
# H1 — PreToolUse path-deny hook for Edit|Write|MultiEdit|NotebookEdit.
# Rejects writes to scope-guarded paths. Exit 2 blocks even in bypassPermissions.
# Kit reference: docs/runbooks/kit-hardening-v1.md
set -euo pipefail

# Read the tool call JSON from stdin.
input=$(cat)
file_path=$(printf '%s' "$input" | python3 -c '
import json, sys
try:
    data = json.load(sys.stdin)
    print(data.get("tool_input", {}).get("file_path", ""))
except Exception:
    print("")
' 2>/dev/null || printf '')

# Empty path? Let it through (nothing to protect).
[ -z "$file_path" ] && exit 0

# Bypass for humans executing from a TTY with an explicit env var.
# Not available to Claude — Claude runs hooks without a TTY.
if [ "${KIT_SKIP_PATH_PROTECT:-0}" = "1" ] && [ -t 0 ]; then
  exit 0
fi

# Absolute → relative (strip project root) for matching.
proj="${CLAUDE_PROJECT_DIR:-$PWD}"
rel="${file_path#$proj/}"

# Protected globs. Order: most-specific first for readable errors.
PROTECTED=(
  "src/components/welcome/*"   # scope guard #5 — WelcomeScreen untouched
  "src/pipeline/orchestrator*" # pipeline orchestrator purity
  "src/pipeline/stages/*"      # stage internals
  ".env"
  ".env.*"
  ".git/*"
  ".powerstack4/.phase"        # powerstack4 internal state
  ".powerstack4/.action-count"
  ".taskmaster/tasks/*.json"   # taskmaster managed files
  "package-lock.json"
)

for pattern in "${PROTECTED[@]}"; do
  case "$rel" in
    $pattern)
      cat >&2 <<EOF
BLOCKED by kit-hardening-v1 (H1 pre-edit-protect-paths.sh)

  File:    $rel
  Pattern: $pattern

This path is scope-guarded by the FRAME DocMining Kit. Reasons:
  - src/components/welcome/*  : locked decision #5 — WelcomeScreen untouched
  - src/pipeline/*            : pipeline orchestrator purity
  - .env*, .git/*             : secrets / VCS internals
  - .powerstack4/.*           : powerstack4 counter state — do not hand-edit
  - .taskmaster/tasks/*.json  : Taskmaster-managed; use mcp__task-master__* tools
  - package-lock.json         : regenerated by npm, never hand-edit

If you need to edit this, ask the human. If the human authorized it
interactively, they can set KIT_SKIP_PATH_PROTECT=1 in their shell and re-run.
EOF
      exit 2
      ;;
  esac
done

exit 0
