/**
 * parseUserStories — Extract user stories from refined epic markdown.
 *
 * Parses the "User Stories" section and extracts structured story objects
 * from the markdown format generated by Stage 5 (Mandatory).
 */

export interface ParsedUserStory {
  id: string;
  title: string;
  asA: string;
  iWant: string;
  soThat: string;
  acceptanceCriteria: string[];
  priority: string;
  storyPoints?: number;
  testCases?: string[];
}

/**
 * Extract user stories from epic markdown content.
 * Handles multiple formats:
 * - ### US-001: Title
 * - **As a** role, **I want** action, **So that** benefit
 * - Acceptance Criteria as bullet lists
 */
export function parseUserStories(epicContent: string): ParsedUserStory[] {
  const stories: ParsedUserStory[] = [];

  // Split on story headers (### US-XXX: Title or ### Story Title)
  const storyPattern = /###\s+(US-\d{3}):?\s*(.+?)(?=\n###\s|$)/gs;
  let match: RegExpExecArray | null;

  while ((match = storyPattern.exec(epicContent)) !== null) {
    const id = match[1] ?? `US-${String(stories.length + 1).padStart(3, '0')}`;
    const rest = match[2] ?? '';

    // Extract title (first line)
    const titleLine = (rest.split('\n')[0] ?? '').trim();
    const body = rest.slice(titleLine.length).trim();

    // Parse "As a / I want / So that"
    const asAMatch = /\*\*As a\*\*\s*(.+?)(?:,|\n)/i.exec(body);
    const iWantMatch = /\*\*I want\*\*\s*(.+?)(?:,|\n)/i.exec(body);
    const soThatMatch = /\*\*So that\*\*\s*(.+?)(?:\.|,|\n|$)/i.exec(body);

    // Parse acceptance criteria (bullet list after "Acceptance Criteria")
    const acSection = body.match(/(?:acceptance criteria|ac)[:\s]*\n((?:\s*[-*]\s*.+\n?)+)/i);
    const acceptanceCriteria: string[] = [];
    if (acSection?.[1]) {
      const bullets = acSection[1].match(/[-*]\s*(.+)/g);
      if (bullets) {
        for (const b of bullets) {
          acceptanceCriteria.push(b.replace(/^[-*]\s*/, '').trim());
        }
      }
    }

    // Parse priority
    const priorityMatch = /\*\*Priority\*\*[:\s]*(\w+)/i.exec(body);

    // Parse story points
    const spMatch = /\*\*Story Points\*\*[:\s]*(\d+)/i.exec(body);
    const storyPoints = spMatch ? parseInt(spMatch[1]!, 10) : undefined;

    // Parse test cases
    const tcSection = body.match(/(?:test cases)[:\s]*\n((?:\s*\d+\.\s*.+\n?)+)/i);
    const testCases: string[] = [];
    if (tcSection?.[1]) {
      const lines = tcSection[1].match(/\d+\.\s*(.+)/g);
      if (lines) {
        for (const line of lines) {
          testCases.push(line.replace(/^\d+\.\s*/, '').trim());
        }
      }
    }

    stories.push({
      id,
      title: titleLine,
      asA: asAMatch?.[1]?.trim() ?? 'user',
      iWant: iWantMatch?.[1]?.trim() ?? titleLine,
      soThat: soThatMatch?.[1]?.trim() ?? 'achieve the goal',
      acceptanceCriteria: acceptanceCriteria.length > 0 ? acceptanceCriteria : ['Functionality works as described'],
      priority: priorityMatch?.[1]?.toLowerCase() ?? 'medium',
      ...(storyPoints !== undefined ? { storyPoints } : {}),
      ...(testCases.length > 0 ? { testCases } : {}),
    });
  }

  // Fallback: if no ### US-XXX pattern found, try simpler bullet-based parsing
  if (stories.length === 0) {
    const bulletStories = epicContent.match(/[-*]\s*\*\*US-\d{3}\*\*[:\s]*(.+)/g);
    if (bulletStories) {
      bulletStories.forEach((line, i) => {
        const idMatch = line.match(/US-(\d{3})/);
        const titleMatch = line.match(/\*\*US-\d{3}\*\*[:\s]*(.+)/);
        stories.push({
          id: `US-${idMatch?.[1] ?? String(i + 1).padStart(3, '0')}`,
          title: titleMatch?.[1]?.trim() ?? line.replace(/^[-*]\s*/, '').trim(),
          asA: 'user',
          iWant: titleMatch?.[1]?.trim() ?? 'this feature',
          soThat: 'achieve the goal',
          acceptanceCriteria: ['Functionality works as described'],
          priority: 'medium',
        });
      });
    }
  }

  return stories;
}
