/**
 * StreamEpicStep — Step 2 of the Extreme Initiative wizard.
 *
 * Two-column layout: editable textarea (left) and rendered preview (right).
 * Auto-generates a stream epic via AI on mount if markdown is empty.
 */

import { useEffect, useRef, useState, useCallback } from 'react';
import { useInitiativeStore } from '@/stores/initiativeStore';
import { useConfigStore } from '@/stores/configStore';
import { generateStreamEpic } from '@/services/ai/initiative/generateStreamEpic';

// ─── Styles ────────────────────────────────────────────────

const FONT_STACK = "Frutiger, 'Helvetica Neue', Helvetica, Arial, sans-serif";

const containerStyle: React.CSSProperties = {
  display: 'flex',
  flexDirection: 'column',
  flex: 1,
  overflow: 'hidden',
  fontFamily: FONT_STACK,
};

const columnsStyle: React.CSSProperties = {
  display: 'flex',
  flex: 1,
  gap: 16,
  overflow: 'hidden',
};

const columnStyle: React.CSSProperties = {
  flex: 1,
  display: 'flex',
  flexDirection: 'column',
  overflow: 'hidden',
};

const textareaStyle: React.CSSProperties = {
  flex: 1,
  border: '1px solid #CCCABC',
  borderRadius: 6,
  fontFamily: 'monospace',
  fontSize: 13,
  padding: 12,
  resize: 'vertical',
  outline: 'none',
};

const previewContainerStyle: React.CSSProperties = {
  flex: 1,
  overflow: 'auto',
  border: '1px solid #CCCABC',
  borderRadius: 6,
  padding: 16,
  backgroundColor: '#FAFAF8',
};

const footerStyle: React.CSSProperties = {
  display: 'flex',
  justifyContent: 'space-between',
  alignItems: 'center',
  paddingTop: 16,
  borderTop: '1px solid #EEEDEB',
  marginTop: 16,
};

const btnBase: React.CSSProperties = {
  fontFamily: FONT_STACK,
  fontSize: 14,
  padding: '8px 20px',
  borderRadius: 6,
  cursor: 'pointer',
  border: '1px solid #CCCABC',
  background: '#fff',
};

const btnPrimary: React.CSSProperties = {
  ...btnBase,
  background: '#1A1A1A',
  color: '#fff',
  border: '1px solid #1A1A1A',
};

// ─── Markdown Preview ──────────────────────────────────────

function renderMarkdownLine(line: string, idx: number): React.ReactNode {
  if (line.startsWith('### ')) {
    return <h3 key={idx} style={{ margin: '12px 0 4px', fontSize: 15 }}>{line.slice(4)}</h3>;
  }
  if (line.startsWith('## ')) {
    return <h2 key={idx} style={{ margin: '16px 0 6px', fontSize: 17 }}>{line.slice(3)}</h2>;
  }
  if (line.trim() === '') {
    return <br key={idx} />;
  }
  return <p key={idx} style={{ margin: '2px 0', fontSize: 14, lineHeight: 1.5 }}>{line}</p>;
}

// ─── Component ─────────────────────────────────────────────

export default function StreamEpicStep() {
  const {
    streamEpicMarkdown,
    headers,
    crews,
    title,
    description,
    setStreamEpic,
    parseHeadersFromEpic,
    setStep,
  } = useInitiativeStore();

  const config = useConfigStore((s) => s.config);

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const autoGenerated = useRef(false);

  const doGenerate = useCallback(async () => {
    setLoading(true);
    setError(null);
    const crewCount = Math.max(crews.length, 2);
    const crewNames = crews.map((c) => c.name).filter(Boolean);
    const enrichedDesc = crewNames.length > 0
      ? `${description}\n\nCrews: ${crewNames.join(', ')}`
      : description;
    const result = await generateStreamEpic(
      config.ai.azure,
      config.endpoints.azureEndpoint,
      title,
      enrichedDesc,
      crewCount,
    );
    if (result.ok) {
      setStreamEpic(result.data);
      parseHeadersFromEpic();
    } else {
      setError(result.error);
    }
    setLoading(false);
  }, [config, title, description, crews.length, setStreamEpic, parseHeadersFromEpic]);

  // Auto-generate on mount if markdown is empty
  useEffect(() => {
    if (!streamEpicMarkdown && !autoGenerated.current) {
      autoGenerated.current = true;
      doGenerate();
    }
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  const handleTextChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setStreamEpic(e.target.value);
  };

  const handleAdvance = () => {
    parseHeadersFromEpic();
    setStep('splitCrews');
  };

  const canAdvance =
    streamEpicMarkdown.trim().length > 0 &&
    headers.length > 0 &&
    crews.length >= 2;

  return (
    <div style={containerStyle} data-testid="stream-epic-step">
      {/* Header row */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 }}>
        <h3 style={{ margin: 0, fontFamily: FONT_STACK }}>Stream Epic</h3>
        <button
          style={btnBase}
          onClick={doGenerate}
          disabled={loading}
        >
          {loading ? 'Generating...' : 'Re-generate'}
        </button>
      </div>

      {error && (
        <div style={{ color: '#C0392B', fontSize: 13, marginBottom: 8 }}>
          Error: {error}
        </div>
      )}

      {/* Two-column layout */}
      <div style={columnsStyle}>
        {/* Left: editable textarea */}
        <div style={columnStyle}>
          {loading && !streamEpicMarkdown ? (
            <div style={{ ...previewContainerStyle, display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#888' }}>
              Generating stream epic...
            </div>
          ) : (
            <textarea
              data-testid="stream-epic-textarea"
              style={textareaStyle}
              value={streamEpicMarkdown}
              onChange={handleTextChange}
              placeholder="Markdown epic content will appear here..."
            />
          )}
        </div>

        {/* Right: rendered preview */}
        <div style={columnStyle}>
          <div style={previewContainerStyle} data-testid="stream-epic-preview">
            {streamEpicMarkdown
              ? streamEpicMarkdown.split('\n').map(renderMarkdownLine)
              : <span style={{ color: '#999' }}>Preview will appear once content is generated.</span>
            }
          </div>
        </div>
      </div>

      {/* Footer navigation */}
      <div style={footerStyle}>
        <button style={btnBase} onClick={() => setStep('init')}>
          &larr; Back
        </button>
        <button
          style={{
            ...btnPrimary,
            ...(canAdvance ? {} : { opacity: 0.4, cursor: 'not-allowed' }),
          }}
          disabled={!canAdvance}
          onClick={handleAdvance}
        >
          Split into Crews &rarr;
        </button>
      </div>
    </div>
  );
}
