{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "frame-spa.fullname" . }}
  labels:
    {{- include "frame-spa.labels" . | nindent 4 }}
{{- end }}
